package edu.nku.csc540.hashtag.model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName = "hashtagAppUserTable")
public class User {
	private String id;
	private String username;
	private String password;
	private String fName;
	private String lName;
	private String email;
	
	public User(){}

	public User(String firstName, String lastName, String email, String username, String password) {
		this.fName = firstName;
		this.lName = lastName;
		this.email = email;
		this.username = username;
		this.password = password;
	}

	@DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
	public String getId() { return id; }
	public void setId(String id) { this.id = id; }

	@DynamoDBAttribute(attributeName="Username")
	public String getUsername() { return username; }
	public void setUsername(String username) { this.username = username; }
	
	@DynamoDBAttribute(attributeName="Password")
	public String getPassword() { return password; }
	public void setPassword(String password) { this.password = password; }

	@DynamoDBAttribute(attributeName="First Name")
	public String getfName() { return fName; }
	public void setfName(String fName) { this.fName = fName; }

	@DynamoDBAttribute(attributeName="Last Name")
	public String getlName() { return lName; }
	public void setlName(String lName) { this.lName = lName; }

	@DynamoDBAttribute(attributeName="Email")
	public String getEmail() { return email; }
	public void setEmail(String email) { this.email = email; }
	
	@Override
	public String toString(){
		return this.getId() + ": " + this.getUsername() + ", " + this.getPassword() + ", " 
				+this.getfName() + " " + this.getlName() + ", " + this.getEmail();
	}
}

